spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    com.example.demo: DEBUG

server:
  port: 8080

flyway:
  enabled: false